import { useState } from "react";
import ReactMarkdown from "react-markdown";
import { ChevronDown } from "lucide-react";
import type { QueryResponse, SourceType } from "@/types/api";
import { getSourceConfig } from "@/lib/sources";
import CitationCard from "./CitationCard";

interface AnswerCardProps {
  data: QueryResponse;
}

const AnswerCard = ({ data }: AnswerCardProps) => {
  const [citationsOpen, setCitationsOpen] = useState(true);

  // Collect unique source types
  const uniqueSources = [...new Set(data.citations.map((c) => c.source_type))] as SourceType[];

  // Replace [N] with superscript-style link
  const processedAnswer = data.answer.replace(
    /\[(\d+)\]/g,
    (_, num) => `[<sup>${num}</sup>](#citation-${num})`
  );

  return (
    <div className="w-full max-w-[760px] mx-auto px-4 sm:px-8 animate-fade-up">
      <div className="bg-card rounded-xl border border-border overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-300">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-border">
          <div className="flex items-center gap-2">
            <span className="text-lg">🩺</span>
            <span className="font-semibold text-foreground">Clinical Answer</span>
          </div>
          <div className="flex items-center gap-1.5 flex-wrap justify-end">
            {uniqueSources.map((src) => {
              const config = getSourceConfig(src);
              return (
                <span
                  key={src}
                  className={`text-[11px] font-medium px-2 py-0.5 rounded-full text-white ${config.colorClass}`}
                >
                  {config.label}
                </span>
              );
            })}
          </div>
        </div>

        {/* Answer body */}
        <div className="p-5">
          <div className="bg-primary-light/50 rounded-lg p-4 prose prose-sm prose-slate max-w-none text-[15px] leading-[1.7]">
            <ReactMarkdown
              components={{
                a: ({ children, href, ...props }) => (
                  <a
                    {...props}
                    href={href}
                    className="text-primary hover:underline no-underline"
                    onClick={(e) => {
                      if (href?.startsWith('#citation-')) {
                        e.preventDefault();
                        const el = document.getElementById(href.slice(1));
                        el?.scrollIntoView({ behavior: 'smooth', block: 'center' });
                      }
                    }}
                  >
                    {children}
                  </a>
                ),
                sup: ({ children }) => (
                  <sup className="text-[11px] font-semibold text-primary cursor-pointer hover:text-primary-hover transition-colors">
                    {children}
                  </sup>
                ),
              }}
            >
              {processedAnswer}
            </ReactMarkdown>
          </div>

          <p className="text-xs text-muted-foreground mt-3">
            Generated by {data.model} · {data.chunks_retrieved} sources retrieved
          </p>
        </div>

        {/* Citations */}
        {data.citations.length > 0 && (
          <div className="border-t border-border">
            <button
              onClick={() => setCitationsOpen(!citationsOpen)}
              className="w-full flex items-center justify-between px-5 py-3 text-sm font-semibold text-foreground hover:bg-muted/30 transition-colors"
            >
              <span>📚 Sources Used ({data.citations.length})</span>
              <ChevronDown className={`w-4 h-4 transition-transform ${citationsOpen ? "rotate-180" : ""}`} />
            </button>
            {citationsOpen && (
              <div className="px-5 pb-5 space-y-3">
                {data.citations.map((citation, i) => (
                  <div
                    key={citation.index}
                    className="animate-fade-up"
                    style={{ animationDelay: `${i * 0.05}s` }}
                  >
                    <CitationCard citation={citation} />
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default AnswerCard;
